# Generated by Django 2.2.3 on 2019-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantModel',
            fields=[
                ('Merchant_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Merchant_Name', models.CharField(max_length=30)),
                ('Merchant_Contact', models.IntegerField(unique=True)),
                ('Merchant_Email', models.EmailField(max_length=254, unique=True)),
                ('Merchant_Password', models.CharField(max_length=60)),
            ],
        ),
    ]
